# stack: serverless-deploymentbucket
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
       "Fn::Join":
         - ""
         - - "sls-deploymentbucket-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: serverless-deployment-bucket
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      VersioningConfiguration:
         Status: Enabled

Outputs:
  DeploymentBucketName:
    Description: Name of Bucket
    Value: !Ref DeploymentBucket
