# stack: committee-sync-queue
Resources:
  CommitteeSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: committee-sync-queue
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: committee-sync-queue
Outputs:
  QueueName:
    Description: The name of the Queue
    Value: !GetAtt CommitteeSyncQueue.QueueName
