---
docs_dir: docs
edit_uri: edit/master/docs
repo_url: https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor
site_description: Docs for serverless-advancedanalytics-fec-data-collection
site_name: serverless-advancedanalytics-fec-data-collection

markdown_extensions:
    - toc

nav:
  - Home: 'README.md'
  - Data: 'DATA.md'
  - Eng: 'ENG.md'
  - Ops: 'OPS.md'

plugins:
  - search

theme:
  name: mkdocs
  include_sidebar: false
  navigation_depth: 4
  nav_style: dark
