Description: Prerequisite AWS Resources for FEC Data-sync serverless functions

Parameters:
  Version:
    Default: v0.0.1
    Description: Code verison, see bin/deploy.sh
    Type: String
  DeadLetterQueueMessageRetentionPeriod:
    Default: 604800 # 7 days in seconds
    Type: Number
  CopyFromBucketName:
    Default: copy-from
    Description: Name for bucket that will be used with COPY FROM command to inert data to redshift
    Type: String
  FilingDeadLetterQueueName:
    Default: filing-dead-letter-queue
    Type: String
  CommitteeDeadLetterQueueName:
    Default: committee-dead-letter-queue
    Type: String
  CandidateDeadLetterQueueName:
    Default: candidate-dead-letter-queue
    Type: String
  DeploymentBucketName:
    Default: serverless-deploymentbucket
    Description: S3 bucket used to deploy serverless stack
    Type: String
  CandidateSyncQueueName:
    Default: candidate-sync-queue
    Description: Name of Queue with Candidates from Sync lambda
    Type: String
  CommitteeSyncQueueName:
    Default: committee-sync-queue
    Description: Name of Queue with Committee from Sync lambda
    Type: String
  NewFilingQueueName:
    Default: fec-new-filing-queue
    Description: Name of Queue for new filings, processed for Financial Summary
    Type: String
  NewFilingQueueSEName:
    Default: fec-new-filing-se-queue
    Description: Queue for new filings, consumed by loader for Schedule E FEC filings
    Type: String
  SupplementalDataQueueName:
    Default: fec-new-filing-supplemental-data-queue
    Description: Name of Queue for new filings to be processed for supplemental FEC filings
    Type: String
  TransactionLoadingQueueName:
    Default: fec-transaction-loading-queue
    Description: Queue for new filings, consumed by loader for Schedule B FEC filings
    Type: String
  RSSFeedTopicName:
    Default: fec-new-filing-rss-fanout
    Description: Name of SNS topic which fans out from new filing RSS feed sync
    Type: String

Resources:

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      BucketName:
       "Fn::Join":
         - ""
         - - Ref: DeploymentBucketName
           - "-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value:
          Ref: DeploymentBucketName
      - Key: Version
        Value: !Ref Version
      VersioningConfiguration:
         Status: Enabled

  CopyFromBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      BucketName:
       "Fn::Join":
         - ""
         - - Ref: CopyFromBucketName
           - "-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value:
          Ref: CopyFromBucketName
      - Key: Version
        Value: !Ref Version
      VersioningConfiguration:
         Status: Enabled

  CommitteeDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref DeadLetterQueueMessageRetentionPeriod
      QueueName: !Ref CommitteeDeadLetterQueueName
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref CommitteeDeadLetterQueueName
      - Key: Version
        Value: !Ref Version

  FilingDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref DeadLetterQueueMessageRetentionPeriod
      QueueName: !Ref FilingDeadLetterQueueName
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref FilingDeadLetterQueueName
      - Key: Version
        Value: !Ref Version

  CandidateDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref DeadLetterQueueMessageRetentionPeriod
      QueueName: !Ref CandidateDeadLetterQueueName
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref CandidateDeadLetterQueueName
      - Key: Version
        Value: !Ref Version

  CandidateSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref CandidateSyncQueueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CandidateDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref CandidateSyncQueueName
      - Key: Version
        Value: !Ref Version

  CommitteeSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref CommitteeSyncQueueName
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CommitteeDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref CommitteeSyncQueueName
      - Key: Version
        Value: !Ref Version

  NewFilingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewFilingQueueName
      VisibilityTimeout: 90
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref NewFilingQueueName
      - Key: Version
        Value: !Ref Version

  NewFilingQueueSE:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewFilingQueueSEName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref NewFilingQueueSEName
      - Key: Version
        Value: !Ref Version

  SupplementalDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SupplementalDataQueueName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref SupplementalDataQueueName
      - Key: Version
        Value: !Ref Version

  TransactionLoadingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref TransactionLoadingQueueName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref TransactionLoadingQueueName
      - Key: Version
        Value: !Ref Version

  RSSFeedTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref RSSFeedTopicName
      Subscription:
        - Endpoint: !GetAtt NewFilingQueueSE.Arn
          Protocol: "sqs"
        - Endpoint: !GetAtt NewFilingQueue.Arn
          Protocol: "sqs"
        - Endpoint: !GetAtt SupplementalDataQueue.Arn
          Protocol: "sqs"
        - Endpoint: !GetAtt TransactionLoadingQueue.Arn
          Protocol: "sqs"
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref RSSFeedTopicName
      - Key: Version
        Value: !Ref Version

  RSSFanoutQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref NewFilingQueue
        - !Ref NewFilingQueueSE
        - !Ref TransactionLoadingQueue
        - !Ref SupplementalDataQueue
      PolicyDocument:
        Statement:
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt NewFilingQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt TransactionLoadingQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt NewFilingQueueSE.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt SupplementalDataQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic

Outputs:

  CopyFromBucketArn:
    Description: The ARN of the bucket for COPY FROM file to be written to
    Value: !GetAtt CopyFromBucket.Arn

  CopyFromBucketName:
    Description: The name of the bucket for COPY FROM file to be written to
    Value: !Ref CopyFromBucket

  CandidateSyncQueueArn:
    Description: The Arn of the Queue for candidates that just filed
    Value: !GetAtt CandidateSyncQueue.Arn

  CandidateSyncQueueName:
    Description: The name of the Queue for candidates that just filed
    Value: !GetAtt CandidateSyncQueue.QueueName

  CommitteeSyncQueueArn:
    Description: The Arn of the Queue for committees that just filed
    Value: !GetAtt CommitteeSyncQueue.Arn

  CommitteeSyncQueueName:
    Description: The name of the Queue for committees that just filed
    Value: !GetAtt CommitteeSyncQueue.QueueName

  DeploymentBucketName:
    Description: Name of Bucket which Serverless CloudFormation is deployed to
    Value: !Ref DeploymentBucket

  NewFilingQueueArn:
    Description: Arn of Queue for new Schedule B RSS filings
    Value: !GetAtt NewFilingQueue.Arn

  NewFilingQueueName:
    Description: Name of Queue for new Schedule B RSS filings
    Value: !GetAtt NewFilingQueue.QueueName

  NewFilingQueueSEArn:
    Description: Arn of Queue for new Schedule E RSS filings
    Value: !GetAtt NewFilingQueueSE.Arn

  NewFilingQueueSEName:
    Description: Name of Queue for new Schedule E RSS filings
    Value: !GetAtt NewFilingQueueSE.QueueName

  SupplementalDataQueueArn:
    Value: !GetAtt SupplementalDataQueue.Arn

  SupplementalDataQueueName:
    Value: !GetAtt SupplementalDataQueue.QueueName

  TransactionLoadingQueueArn:
    Value: !GetAtt TransactionLoadingQueue.Arn

  TransactionLoadingQueueName:
    Value: !GetAtt TransactionLoadingQueue.QueueName

  RSSFeedTopicArn:
    Description: Arn of SNS Topic for new new RSS filings
    Value: !Ref RSSFeedTopic

  Version:
    Description: see bin/deploy.sh
    Value: !Ref Version
