Description: Prerequisite AWS Resources for FEC Data-sync serverless functions

Parameters:
  Version:
    Default: v0.0.1
    Description: Code verison, see bin/deploy.sh
    Type: String

  DeploymentBucketName:
    Default: serverless-deploymentbucket
    Type: String
  CommitteeSyncQueueName:
    Default: committee-sync-queue
    Type: String
  NewFilingQueueName:
    Default: fec-new-filing-queue
    Type: String
  RSSFeedTopicName:
    Default: fec-new-filing
    Type: String

Resources:

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      BucketName:
       "Fn::Join":
         - ""
         - - Ref: DeploymentBucketName
           - "-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value:
          Ref: DeploymentBucketName
      - Key: Version
        Value: !Ref Version
      VersioningConfiguration:
         Status: Enabled

  CommitteeSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref CommitteeSyncQueueName
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref CommitteeSyncQueueName
      - Key: Version
        Value: !Ref Version

  NewFilingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref NewFilingQueueName
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref NewFilingQueueName
      - Key: Version
        Value: !Ref Version

  RSSFeedTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref RSSFeedTopicName
      Subscription:
        - Endpoint: !GetAtt NewFilingQueue.Arn
          Protocol: "sqs"
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: !Ref RSSFeedTopicName
      - Key: Version
        Value: !Ref Version

  NewFilingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [ !Ref NewFilingQueue ]
      PolicyDocument:
        Statement:
          Action:
          - sqs:SendMessage
          Effect: Allow
          Principal: "*"
          Resource: !GetAtt NewFilingQueue.Arn
          Condition:
           ArnEquals:
            aws:SourceArn: !Ref RSSFeedTopic

Outputs:

  CommitteeSyncQueueArn:
    Description: The Arn of the Queue for committees that just filed
    Value: !GetAtt CommitteeSyncQueue.Arn

  CommitteeSyncQueueName:
    Description: The name of the Queue for committees that just filed
    Value: !GetAtt CommitteeSyncQueue.QueueName

  DeploymentBucketName:
    Description: Name of Bucket which Serverless CloudFormation is deployed to
    Value: !Ref DeploymentBucket

  NewFilingQueueArn:
    Description: Arn of Queue for new new RSS filings
    Value: !GetAtt NewFilingQueue.Arn

  NewFilingQueueName:
    Description: Name of Queue for new new RSS filings
    Value: !GetAtt NewFilingQueue.QueueName

  RSSFeedTopicArn:
    Description: Arn of SNS Topic for new new RSS filings
    Value: !Ref RSSFeedTopic

  Version:
    Description: see bin/deploy.sh
    Value: !Ref Version
