Description: Prerequisite AWS Resources for FEC Data-sync serverless functions

Parameters:
  DeadLetterQueueMessageRetentionPeriod:
    Default: 1209600 # 604800 # 7 days in seconds
    Type: Number
  CopyFromBucketName:
    Default: copy-from
    Description: Name for bucket that will be used with COPY FROM command to inert data to redshift
    Type: String
  FilingDeadLetterQueueName:
    Default: filing-dead-letter-queue
    Type: String
  CommitteeDeadLetterQueueName:
    Default: committee-dead-letter-queue
    Type: String
  CandidateDeadLetterQueueName:
    Default: candidate-dead-letter-queue
    Type: String
  DeploymentBucketName:
    Default: serverless-deploymentbucket
    Description: S3 bucket used to deploy serverless stack
    Type: String
  CandidateSyncQueueName:
    Default: candidate-sync-queue
    Description: Name of Queue with Candidates from Sync lambda
    Type: String
  CommitteeSyncQueueName:
    Default: committee-sync-queue
    Description: Name of Queue with Committee from Sync lambda
    Type: String
  FinancialSummaryQueueName:
    Default: fec-financialsummary-queue
    Description: Name of Queue for new filings, processed for Financial Summary
    Type: String
  FilingRedriveCount:
    Default: 5
    Type: Number
  FilingSEQueueName:
    Default: fec-se-queue
    Description: Queue for new filings, consumed by loader for Schedule E FEC filings
    Type: String
  FilingF1SQueueName:
    Default: fec-f1s-queue
    Description: Name of Queue for new filings to be processed for supplemental FEC filings
    Type: String
  FilingSBQueueName:
    Default: fec-sb-queue
    Description: Queue for new filings, consumed by loader for Schedule B FEC filings
    Type: String
  RSSFeedTopicName:
    Default: fec-new-filing-rss-fanout
    Description: Name of SNS topic which fans out from new filing RSS feed sync
    Type: String

Resources:

########################################
# S3 Buckets
########################################

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      BucketName:
       "Fn::Join":
         - ""
         - - Ref: DeploymentBucketName
           - "-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      Tags:
      - Key: Name
        Value:
          Ref: DeploymentBucketName
      VersioningConfiguration:
         Status: Enabled

  CopyFromBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      BucketName:
       "Fn::Join":
         - ""
         - - Ref: CopyFromBucketName
           - "-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      Tags:
      - Key: Name
        Value:
          Ref: CopyFromBucketName
      VersioningConfiguration:
         Status: Enabled

########################################
# Candidate data stream
########################################

  CandidateDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod:
        Ref: DeadLetterQueueMessageRetentionPeriod
      QueueName: !Ref CandidateDeadLetterQueueName
      Tags:
      - Key: Name
        Value: !Ref CandidateDeadLetterQueueName

  CandidateSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref CandidateSyncQueueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CandidateDeadLetterQueue.Arn
        maxReceiveCount: 15
      Tags:
      - Key: Name
        Value: !Ref CandidateSyncQueueName

########################################
# Committee data stream
########################################

  CommitteeDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Ref CommitteeDeadLetterQueueName
      Tags:
      - Key: Name
        Value: !Ref CommitteeDeadLetterQueueName

  CommitteeSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref CommitteeSyncQueueName
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CommitteeDeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
      - Key: Name
        Value: !Ref CommitteeSyncQueueName

########################################
# Filing data stream
########################################

  FinancialSummaryDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  FinancialSummaryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref FinancialSummaryQueueName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FinancialSummaryDLQueue.Arn
        maxReceiveCount: 5
        # maxReceiveCount: !Ref FilingRedriveCount
      Tags:
      - Key: Name
        Value: !Ref FinancialSummaryQueueName

  FilingSEDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  FilingSEQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref FilingSEQueueName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingSEDLQueue.Arn
        # maxReceiveCount: !Ref FilingRedriveCount
        maxReceiveCount: 5
      Tags:
      - Key: Name
        Value: !Ref FilingSEQueueName

  FilingF1SDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  FilingF1SQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref FilingF1SQueueName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingF1SDLQueue.Arn
        # maxReceiveCount: !Ref FilingRedriveCount
        maxReceiveCount: 5
      Tags:
      - Key: Name
        Value: !Ref FilingF1SQueueName

  FilingSBDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  FilingSBQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref FilingSBQueueName
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilingSBDLQueue.Arn
        # maxReceiveCount: !Ref FilingRedriveCount
        maxReceiveCount: 5
      Tags:
      - Key: Name
        Value: !Ref FilingSBQueueName

  RSSFeedTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref RSSFeedTopicName
      Subscription:
        - Endpoint: !GetAtt FilingSEQueue.Arn
          Protocol: "sqs"
        - Endpoint: !GetAtt FinancialSummaryQueue.Arn
          Protocol: "sqs"
        - Endpoint: !GetAtt FilingF1SQueue.Arn
          Protocol: "sqs"
        - Endpoint: !GetAtt FilingSBQueue.Arn
          Protocol: "sqs"
      Tags:
      - Key: Name
        Value: !Ref RSSFeedTopicName

  RSSFanoutQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FinancialSummaryQueue
        - !Ref FilingSEQueue
        - !Ref FilingSBQueue
        - !Ref FilingF1SQueue
      PolicyDocument:
        Statement:
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt FinancialSummaryQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt FilingSBQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt FilingSEQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic
          - Action:
            - sqs:SendMessage
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt FilingF1SQueue.Arn
            Condition:
             ArnEquals:
              aws:SourceArn: !Ref RSSFeedTopic

Outputs:

  CopyFromBucketArn:
    Description: The ARN of the bucket for COPY FROM file to be written to
    Value: !GetAtt CopyFromBucket.Arn

  CopyFromBucketName:
    Description: The name of the bucket for COPY FROM file to be written to
    Value: !Ref CopyFromBucket

  CandidateSyncQueueArn:
    Description: The Arn of the Queue for candidates that just filed
    Value: !GetAtt CandidateSyncQueue.Arn

  CandidateSyncQueueName:
    Description: The name of the Queue for candidates that just filed
    Value: !GetAtt CandidateSyncQueue.QueueName

  CommitteeSyncQueueArn:
    Description: The Arn of the Queue for committees that just filed
    Value: !GetAtt CommitteeSyncQueue.Arn

  CommitteeSyncQueueName:
    Description: The name of the Queue for committees that just filed
    Value: !GetAtt CommitteeSyncQueue.QueueName

  DeploymentBucketName:
    Description: Name of Bucket which Serverless CloudFormation is deployed to
    Value: !Ref DeploymentBucket

  FinancialSummaryQueueArn:
    Value: !GetAtt FinancialSummaryQueue.Arn

  FinancialSummaryQueueName:
    Value: !GetAtt FinancialSummaryQueue.QueueName

  FilingSEQueueArn:
    Value: !GetAtt FilingSEQueue.Arn

  FilingSEQueueName:
    Value: !GetAtt FilingSEQueue.QueueName

  FilingF1SQueueArn:
    Value: !GetAtt FilingF1SQueue.Arn

  FilingF1SQueueName:
    Value: !GetAtt FilingF1SQueue.QueueName

  FilingSBQueueArn:
    Value: !GetAtt FilingSBQueue.Arn

  FilingSBQueueName:
    Value: !GetAtt FilingSBQueue.QueueName

  RSSFeedTopicArn:
    Description: Arn of SNS Topic for new new RSS filings
    Value: !Ref RSSFeedTopic
