Description: Prerequisite AWS Resources for FEC Data-sync serverless functions
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
       "Fn::Join":
         - ""
         - - "serverless-deploymentbucket-"
           - Ref: "AWS::Region"
           - "-"
           - Ref: "AWS::AccountId"
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: serverless-deployment-bucket
      BucketEncryption:
         ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: "AES256"
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      VersioningConfiguration:
         Status: Enabled

  CommitteeSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: committee-sync-queue
      Tags:
      - Key: managed_by
        Value: CloudFormation
      - Key: Project
        Value: FEC Data-sync
      - Key: created_by
        Value: sblack@rhythmictech.com
      - Key: Name
        Value: committee-sync-queue

Outputs:
  QueueName:
    Description: The name of the Queue
    Value: !GetAtt CommitteeSyncQueue.QueueName
  DeploymentBucketName:
    Description: Name of Bucket
    Value: !Ref DeploymentBucket
