from psycopg2 import sql
from psycopg2.sql import SQL

def get_committeecandidates_insert_statement(committee_id: str, candidate_id: str) -> SQL:
    query = sql.SQL('''
INSERT INTO committeecandidates(committee_id, candidate_id)
VALUES (%s, %s)
    ''').format(committee_id, candidate_id)
    return query

def get_committeedetail_insert_statement(
    affiliated_committee_name
    , city
    , committee_candidate_id
    , committee_id
    , committee_name
    , committee_type
    , committee_type_full
    , custodian_city
    , custodian_name_1
    , custodian_name_2
    , custodian_name_full
    , custodian_name_middle
    , custodian_name_prefix
    , custodian_name_suffix
    , custodian_name_title
    , custodian_phone
    , custodian_state
    , custodian_street_1
    , custodian_street_2
    , custodian_zip
    , cycles
    , designation
    , designation_full
    , email
    , fax
    , filing_frequency
    , first_file_date
    , form_type
    , last_file_date
    , last_updated
    , leadership_pac
    , lobbyist_registrant_pac
    , organization_type
    , organization_type_full
    , party
    , party_full
    , party_type
    , party_type_full
    , state
    , state_full
    , street_1
    , street_2
    , treasurer_city
    , treasurer_name
    , treasurer_name_1
    , treasurer_name_2
    , treasurer_name_middle
    , treasurer_name_prefix
    , treasurer_name_suffix
    , treasurer_name_title
    , treasurer_phone
    , treasurer_state
    , treasurer_street_1
    , treasurer_street_2
    , treasurer_zip
    , website
    , zip):
    query = sql.SQL('''
INSERT INTO committeedetail(
    affiliated_committee_name
    , city
    , committee_candidate_id
    , committee_id
    , committee_name
    , committee_type
    , committee_type_full
    , custodian_city
    , custodian_name_1
    , custodian_name_2
    , custodian_name_full
    , custodian_name_middle
    , custodian_name_prefix
    , custodian_name_suffix
    , custodian_name_title
    , custodian_phone
    , custodian_state
    , custodian_street_1
    , custodian_street_2
    , custodian_zip
    , cycles
    , designation
    , designation_full
    , email
    , fax
    , filing_frequency
    , first_file_date
    , form_type
    , last_file_date
    , last_updated
    , leadership_pac
    , lobbyist_registrant_pac
    , organization_type
    , organization_type_full
    , party
    , party_full
    , party_type
    , party_type_full
    , state
    , state_full
    , street_1
    , street_2
    , treasurer_city
    , treasurer_name
    , treasurer_name_1
    , treasurer_name_2
    , treasurer_name_middle
    , treasurer_name_prefix
    , treasurer_name_suffix
    , treasurer_name_title
    , treasurer_phone
    , treasurer_state
    , treasurer_street_1
    , treasurer_street_2
    , treasurer_zip
    , website
    , zip
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ''').format(
    affiliated_committee_name
    , city
    , committee_candidate_id
    , committee_id
    , committee_name
    , committee_type
    , committee_type_full
    , custodian_city
    , custodian_name_1
    , custodian_name_2
    , custodian_name_full
    , custodian_name_middle
    , custodian_name_prefix
    , custodian_name_suffix
    , custodian_name_title
    , custodian_phone
    , custodian_state
    , custodian_street_1
    , custodian_street_2
    , custodian_zip
    , cycles
    , designation
    , designation_full
    , email
    , fax
    , filing_frequency
    , first_file_date
    , form_type
    , last_file_date
    , last_updated
    , leadership_pac
    , lobbyist_registrant_pac
    , organization_type
    , organization_type_full
    , party
    , party_full
    , party_type
    , party_type_full
    , state
    , state_full
    , street_1
    , street_2
    , treasurer_city
    , treasurer_name
    , treasurer_name_1
    , treasurer_name_2
    , treasurer_name_middle
    , treasurer_name_prefix
    , treasurer_name_suffix
    , treasurer_name_title
    , treasurer_phone
    , treasurer_state
    , treasurer_street_1
    , treasurer_street_2
    , treasurer_zip
    , website
    , zip)
    return query
