
CREATE TABLE IF NOT EXISTS fec.committee_totals
(
	all_loans_received NUMERIC(20,9)   ENCODE az64
	,all_other_loans NUMERIC(20,9)   ENCODE az64
	,allocated_federal_election_levin_share NUMERIC(20,9)   ENCODE az64
	,candidate_contribution NUMERIC(20,9)   ENCODE az64
	,cash_on_hand_beginning_period NUMERIC(20,9)   ENCODE az64
	,committee_designation VARCHAR(256)   ENCODE lzo
	,committee_designation_full VARCHAR(256)   ENCODE lzo
	,committee_id VARCHAR(256) NOT NULL  ENCODE lzo
	,committee_name VARCHAR(256)   ENCODE lzo
	,committee_type VARCHAR(256)   ENCODE lzo
	,committee_type_full VARCHAR(256)   ENCODE lzo
	,contribution_refunds NUMERIC(20,9)   ENCODE az64
	,contributions NUMERIC(20,9)   ENCODE az64
	,convention_exp NUMERIC(20,9)   ENCODE az64
	,coordinated_expenditures_by_party_committee NUMERIC(20,9)   ENCODE az64
	,coverage_end_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,coverage_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,"cycle" INTEGER NOT NULL  ENCODE az64
	,disbursements NUMERIC(20,9)   ENCODE az64
	,exempt_legal_accounting_disbursement NUMERIC(20,9)   ENCODE az64
	,exp_prior_years_subject_limits NUMERIC(20,9)   ENCODE az64
	,exp_subject_limits NUMERIC(20,9)   ENCODE az64
	,fed_candidate_committee_contributions NUMERIC(20,9)   ENCODE az64
	,fed_candidate_contribution_refunds NUMERIC(20,9)   ENCODE az64
	,fed_disbursements NUMERIC(20,9)   ENCODE az64
	,fed_election_activity NUMERIC(20,9)   ENCODE az64
	,fed_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,fed_receipts NUMERIC(20,9)   ENCODE az64
	,federal_funds NUMERIC(20,9)   ENCODE az64
	,fundraising_disbursements NUMERIC(20,9)   ENCODE az64
	,independent_expenditures NUMERIC(20,9)   ENCODE az64
	,individual_contributions NUMERIC(20,9)   ENCODE az64
	,individual_itemized_contributions NUMERIC(20,9)   ENCODE az64
	,individual_unitemized_contributions NUMERIC(20,9)   ENCODE az64
	,itemized_convention_exp NUMERIC(20,9)   ENCODE az64
	,itemized_other_disb NUMERIC(20,9)   ENCODE az64
	,itemized_other_income NUMERIC(20,9)   ENCODE az64
	,itemized_other_refunds NUMERIC(20,9)   ENCODE az64
	,itemized_refunds_relating_convention_exp NUMERIC(20,9)   ENCODE az64
	,last_beginning_image_number VARCHAR(256)   ENCODE lzo
	,last_cash_on_hand_end_period NUMERIC(20,9)   ENCODE az64
	,last_debts_owed_by_committee NUMERIC(20,9)   ENCODE az64
	,last_debts_owed_to_committee NUMERIC(20,9)   ENCODE az64
	,last_report_type_full VARCHAR(256)   ENCODE lzo
	,last_report_year INTEGER   ENCODE az64
	,loan_repayments NUMERIC(20,9)   ENCODE az64
	,loan_repayments_candidate_loans NUMERIC(20,9)   ENCODE az64
	,loan_repayments_made NUMERIC(20,9)   ENCODE az64
	,loan_repayments_other_loans NUMERIC(20,9)   ENCODE az64
	,loan_repayments_received NUMERIC(20,9)   ENCODE az64
	,loans NUMERIC(20,9)   ENCODE az64
	,loans_and_loan_repayments_made NUMERIC(20,9)   ENCODE az64
	,loans_and_loan_repayments_received NUMERIC(20,9)   ENCODE az64
	,loans_made NUMERIC(20,9)   ENCODE az64
	,loans_made_by_candidate NUMERIC(20,9)   ENCODE az64
	,loans_received NUMERIC(20,9)   ENCODE az64
	,loans_received_from_candidate NUMERIC(20,9)   ENCODE az64
	,net_contributions NUMERIC(20,9)   ENCODE az64
	,net_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,non_allocated_fed_election_activity NUMERIC(20,9)   ENCODE az64
	,offsets_to_fundraising_expenditures NUMERIC(20,9)   ENCODE az64
	,offsets_to_legal_accounting NUMERIC(20,9)   ENCODE az64
	,offsets_to_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,operating_expenditures NUMERIC(20,9)   ENCODE az64
	,other_disbursements NUMERIC(20,9)   ENCODE az64
	,other_fed_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,other_fed_receipts NUMERIC(20,9)   ENCODE az64
	,other_loans_received NUMERIC(20,9)   ENCODE az64
	,other_political_committee_contributions NUMERIC(20,9)   ENCODE az64
	,other_receipts NUMERIC(20,9)   ENCODE az64
	,other_refunds NUMERIC(20,9)   ENCODE az64
	,party_full VARCHAR(256)   ENCODE lzo
	,pdf_url VARCHAR(256)   ENCODE lzo
	,political_party_committee_contributions NUMERIC(20,9)   ENCODE az64
	,receipts NUMERIC(20,9)   ENCODE az64
	,refunded_individual_contributions NUMERIC(20,9)   ENCODE az64
	,refunded_other_political_committee_contributions NUMERIC(20,9)   ENCODE az64
	,refunded_political_party_committee_contributions NUMERIC(20,9)   ENCODE az64
	,refunds_relating_convention_exp NUMERIC(20,9)   ENCODE az64
	,repayments_loans_made_by_candidate NUMERIC(20,9)   ENCODE az64
	,repayments_other_loans NUMERIC(20,9)   ENCODE az64
	,report_form VARCHAR(256)   ENCODE lzo
	,shared_fed_activity NUMERIC(20,9)   ENCODE az64
	,shared_fed_activity_nonfed NUMERIC(20,9)   ENCODE az64
	,shared_fed_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,shared_nonfed_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,total_exp_subject_limits NUMERIC(20,9)   ENCODE az64
	,total_independent_contributions NUMERIC(20,9)   ENCODE az64
	,total_independent_expenditures NUMERIC(20,9)   ENCODE az64
	,total_offsets_to_operating_expenditures NUMERIC(20,9)   ENCODE az64
	,total_transfers NUMERIC(20,9)   ENCODE az64
	,transaction_coverage_date DATE   ENCODE az64
	,transfers_from_affiliated_committee NUMERIC(20,9)   ENCODE az64
	,transfers_from_affiliated_party NUMERIC(20,9)   ENCODE az64
	,transfers_from_nonfed_account NUMERIC(20,9)   ENCODE az64
	,transfers_from_nonfed_levin NUMERIC(20,9)   ENCODE az64
	,transfers_from_other_authorized_committee NUMERIC(20,9)   ENCODE az64
	,transfers_to_affiliated_committee NUMERIC(20,9)   ENCODE az64
	,transfers_to_other_authorized_committee NUMERIC(20,9)   ENCODE az64
	,unitemized_convention_exp NUMERIC(20,9)   ENCODE az64
	,unitemized_other_disb NUMERIC(20,9)   ENCODE az64
	,unitemized_other_income NUMERIC(20,9)   ENCODE az64
	,unitemized_other_refunds NUMERIC(20,9)   ENCODE az64
	,unitemized_refunds_relating_convention_exp NUMERIC(20,9)   ENCODE az64
	,committee_state VARCHAR(256)   ENCODE lzo
	,filing_frequency VARCHAR(256)   ENCODE lzo
	,filing_frequency_full VARCHAR(256)   ENCODE lzo
	,first_file_date VARCHAR(256)   ENCODE lzo
	,treasurer_name VARCHAR(256)   ENCODE lzo
	,contributions_ie_and_party_expenditures_made_percent VARCHAR(256)   ENCODE lzo
	,organization_type VARCHAR(256)   ENCODE lzo
	,PRIMARY KEY (committee_id, "cycle")
)
DISTSTYLE AUTO
;
