

--
-- Generated from https://github.com/esonderegger/fecfile/blob/master/fecfile/mappings.json
--

SET search_path TO fec;

CREATE TABLE IF NOT EXISTS fec.filings_schedule_e (
    fec_file_id INT(10) NOT NULL,
    amended_cd VARCHAR(100) DEFAULT NULL,
    back_reference_sched_name VARCHAR(100) DEFAULT NULL,
    back_reference_tran_id_number VARCHAR(100) DEFAULT NULL,
    calendar_y_t_d_per_election_office FLOAT DEFAULT NULL,
    candidate_district VARCHAR(100) DEFAULT NULL,
    candidate_first_name VARCHAR(100) DEFAULT NULL,
    candidate_id_number VARCHAR(10) DEFAULT NULL,
    candidate_last_name VARCHAR(100) DEFAULT NULL,
    candidate_middle_name VARCHAR(100) DEFAULT NULL,
    candidate_name VARCHAR(100) DEFAULT NULL,
    candidate_office VARCHAR(100) DEFAULT NULL,
    candidate_prefix VARCHAR(100) DEFAULT NULL,
    candidate_state VARCHAR(100) DEFAULT NULL,
    candidate_suffix VARCHAR(100) DEFAULT NULL,
    category_code VARCHAR(100) DEFAULT NULL,
    completing_first_name VARCHAR(100) DEFAULT NULL,
    completing_last_name VARCHAR(100) DEFAULT NULL,
    completing_middle_name VARCHAR(100) DEFAULT NULL,
    completing_prefix VARCHAR(100) DEFAULT NULL,
    completing_suffix VARCHAR(100) DEFAULT NULL,
    conduit_city VARCHAR(100) DEFAULT NULL,
    conduit_name VARCHAR(100) DEFAULT NULL,
    conduit_state VARCHAR(100) DEFAULT NULL,
    conduit_street_1 VARCHAR(100) DEFAULT NULL,
    conduit_street_2 VARCHAR(100) DEFAULT NULL,
    conduit_zip_code VARCHAR(100) DEFAULT NULL,
    date_notarized DATE DEFAULT NULL,
    date_notary_commission_expires VARCHAR(100) DEFAULT NULL,
    date_signed DATE DEFAULT NULL,
    disbursement_date DATE DEFAULT NULL,
    dissemination_date DATE DEFAULT NULL,
    election_code VARCHAR(100) DEFAULT NULL,
    election_other_description VARCHAR(100) DEFAULT NULL,
    entity_type VARCHAR(100) DEFAULT NULL,
    expenditure_amount FLOAT DEFAULT NULL,
    expenditure_purpose_code VARCHAR(100) DEFAULT NULL,
    expenditure_purpose_descrip VARCHAR(100) DEFAULT NULL,
    filer_committee_id_number VARCHAR(100) DEFAULT NULL,
    form_type VARCHAR(100) DEFAULT NULL,
    image_number VARCHAR(100) DEFAULT NULL,
    ind_name_as_signed VARCHAR(100) DEFAULT NULL,
    ind_name_notary VARCHAR(100) DEFAULT NULL,
    memo_code VARCHAR(100) DEFAULT NULL,
    memo_text_description VARCHAR(100) DEFAULT NULL,
    payee_city VARCHAR(100) DEFAULT NULL,
    payee_cmtte_fec_id_number VARCHAR(100) DEFAULT NULL,
    payee_first_name VARCHAR(100) DEFAULT NULL,
    payee_last_name VARCHAR(100) DEFAULT NULL,
    payee_middle_name VARCHAR(100) DEFAULT NULL,
    payee_name VARCHAR(100) DEFAULT NULL,
    payee_organization_name VARCHAR(100) DEFAULT NULL,
    payee_prefix VARCHAR(100) DEFAULT NULL,
    payee_state VARCHAR(100) DEFAULT NULL,
    payee_street_1 VARCHAR(100) DEFAULT NULL,
    payee_street_2 VARCHAR(100) DEFAULT NULL,
    payee_suffix VARCHAR(100) DEFAULT NULL,
    payee_zip_code VARCHAR(10) DEFAULT NULL,
    support_oppose_code VARCHAR(100) DEFAULT NULL,
    transaction_id_number VARCHAR(100) NOT NULL,
    PRIMARY KEY(transaction_id_number),
    FOREIGN KEY(fec_file_id) REFERENCES filings(fec_file_id),
    FOREIGN KEY(candidate_id_number) REFERENCES candidate_detail(candidate_id)
) DISTSTYLE AUTO;
